### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by goto-bus-stop**
Updates to more recent call-matcher and espurify versions, which don't depend on the big core-js library.

Also updates acorn to the most recent version, which still works on all the same Node.js versions as previously.

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
@twada do you have a moment to merge/release this? there are no breaking changes to the `unassert` API in these updates.

**Comment by falsandtru** [comment]
@goto-bus-stop You should talk @twada on Twitter when he don't respond. I sometimes did so to make him notice a PR.

**Comment by twada** [comment]
@goto-bus-stop @falsandtru Thank you for pinging me and sorry for my late response. I'll go ahead tomorrow (in JST).

**Comment by twada** [comment]
@goto-bus-stop Thank you! Now merged and will be released within a day.

**Comment by goto-bus-stop** [comment]
Thank you :revolving_hearts:

**Comment by twada** [comment]
Released as [1.6.0](https://github.com/unassert-js/unassert/blob/master/CHANGELOG.md#160-2019-09-20). Thanks!

**Pull request merged**
